#!/usr/bin/env python3
import tkinter as tk      
import serial
import time

ser = serial.Serial('/dev/ttyACM0', 9600)    
window = tk.Tk()
window.title("Force Indication/Control Menu")
window.geometry('400x100')

Hbutton = tk.Button(text="High Limits", width=6, height=1, bg="gray", fg="red")
Hbutton.pack(side=tk.LEFT)

Lbutton = tk.Button(text="Low Limits", width=6, height=1, bg="gray", fg="green")
Lbutton.pack(side=tk.LEFT)

Rbutton = tk.Button(text="Retract", width=5, height=2, bg="gray", fg="red")
Rbutton.pack(side=tk.RIGHT)

Ebutton = tk.Button(text="Extend", width=5, height=2, bg="gray", fg="green")
Ebutton.pack(side=tk.RIGHT)

forcelimit = "L"
forcecommand = "LS"
forceimport = "S56789"

forceLabel = tk.Label(text="LS66")
forceLabel.pack(side=tk.TOP)

forceReading = tk.Label(text="5")
forceReading.pack(side=tk.BOTTOM)

#Defining motor controller actions
def handle_low(event):
    global forcelimit
    forcelimit = "L"
    Lbutton.config(relief=tk.SUNKEN)
    Hbutton.config(relief=tk.RAISED)
def handle_high(event):
    global forcelimit
    forcelimit = "H"
    Hbutton.config(relief=tk.SUNKEN)
    Lbutton.config(relief=tk.RAISED)
def handle_extend(event):
    global forcelimit
    global forcecommand
    forcecontrol = "E"
    Ebutton.config(relief=tk.SUNKEN)
    forcecommand = forcelimit + forcecontrol
def handle_retract(event):
    global forcelimit
    global forcecommand
    forcecontrol = "R"
    Rbutton.config(relief=tk.SUNKEN)
    forcecommand = forcelimit + forcecontrol
def handle_stop(event):
    global forcelimit
    global forcecommand
    forcecontrol = "S"
    Ebutton.config(relief=tk.RAISED)
    Rbutton.config(relief=tk.RAISED)
    forcecommand = forcelimit + forcecontrol

def update_serial():
    global forceimport
    global forcecommand
    forceimport = str(ser.readline().decode('utf_8'))
    forceLabel["text"] = forceimport
    ser.write(str(forcecommand).encode('utf_8'))
    forceReading["text"] = forcecommand
    
#Key binds control everything
window.bind("<e>", handle_extend)
window.bind("<r>", handle_retract)
window.bind("<l>", handle_low)
window.bind("<h>", handle_high)
window.bind("<KeyRelease-r>", handle_stop)
window.bind("<KeyRelease-e>", handle_stop)
#window.bind("<0>", update_serial)
Ebutton.bind("<Button-1>", handle_extend)
Ebutton.bind("<ButtonRelease-1>", handle_stop)
Rbutton.bind("<Button-1>", handle_retract)
Rbutton.bind("<ButtonRelease-1>", handle_stop)
Hbutton.bind("<Button-1>", handle_high)
Lbutton.bind("<Button-1>", handle_low)

def main_show():
    update_serial()
    window.update_idletasks()
    window.after_idle(main_show)

main_show()
